# -*- coding: utf-8 -*-
"""Pipeline anamoly detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A9VJWOTYPTisXEBM7PbRGA3HafihEaM7
"""

!pip install streamlit pyngrok pandas numpy matplotlib scikit-learn

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# 
# st.title("Pipeline Anomaly Detection")
# 
# file = st.file_uploader("Upload CSV", type=["csv"])
# 
# if file:
#     df = pd.read_csv(file)
#     st.write(df.head())
# 
#     col = st.selectbox("Select column", df.columns)
# 
#     st.line_chart(df[col])
# 
#     mean = df[col].mean()
#     std = df[col].std()
# 
#     anomalies = df[(df[col] > mean + 2*std) | (df[col] < mean - 2*std)]
#     st.write("Anomalies", anomalies)

!streamlit run app.py &>/dev/null &

import time
time.sleep(5)

from pyngrok import ngrok
ngrok.set_auth_token("3Fm7SeYfsQ5pQJphhsrobsPnOxz_6fABYSvSAtJ7WgQq31c1a")

public_url = ngrok.connect(8501)
print(public_url)